name: Cypress Tests

on: workflow_dispatch

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    name: Artifacts    
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/userNOTRegistered.js
          
      - name: Reporting screenshots    
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Reporting video   
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
